<a href="https://colab.research.google.com/github/kpereira3/GB885_Discussion_7_Pereira_K/blob/main/GGB885_Assignment_7_Pereira_K.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Business Case

You are an analyst for a sports talent agency firm named Jon Paul Sports Management Group (JPSMG). The firm is dedicated to providing athletes and sports professionals with representation leveraged by the power of machine learning and advanced predictive modeling.

In [ ]:
# Import Pandas
import pandas as pd

In [ ]:
# Upload file
from google.colab import files
uploaded = files.upload()

Saving female_olympic_swimmers.csv to female_olympic_swimmers.csv

In [ ]:
# Put CSV into a Dataframe
swimmers = pd.read_csv("female_olympic_swimmers.csv")

In [ ]:
# Check Dataframe
swimmers.head()

,Unnamed: 0,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,474,259,Reema Abdo,F,21.0,173.0,59.0,Canada,CAN,1984 Summer,1984,Summer,Los Angeles,Swimming,Swimming Women's 100 metres Backstroke,NaN
1,475,259,Reema Abdo,F,21.0,173.0,59.0,Canada,CAN,1984 Summer,1984,Summer,Los Angeles,Swimming,Swimming Women's 200 metres Backstroke,NaN
2,476,259,Reema Abdo,F,21.0,173.0,59.0,Canada,CAN,1984 Summer,1984,Summer,Los Angeles,Swimming,Swimming Women's 4 x 100 metres Medley Relay,Bronze
3,517,290,Fatima Abdul Majeed Hameed Al-Kirashi,F,14.0,NaN,NaN,Bahrain,BRN,2000 Summer,2000,Summer,Sydney,Swimming,Swimming Women's 50 metres Freestyle,NaN
4,729,417,Sara Helena berg,F,17.0,190.0,73.0,Sweden,SWE,1988 Summer,1988,Summer,Seoul,Swimming,Swimming Women's 50 metres Freestyle,NaN

In [ ]:
#What country produced the most female Olympic swimmers from 2000 to 2016?
swimmers_2000_2016 = swimmers[(swimmers["Year"] >= 2000) & (swimmers["Year"] <= 2016)]

swimmers_2000_2016["NOC"].value_counts().head(1)

NOC
USA    238
Name: count, dtype: int64

In [ ]:
#Who is the tallest medalist from the 2016 games?
medalists = swimmers[(swimmers["Year"] == 2016) & (swimmers["Medal"].notna())]
medalists.sort_values("Height", ascending=False).head(1)

,Unnamed: 0,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
7460,206160,103490,Cierra Runge,F,20.0,193.0,85.0,United States,USA,2016 Summer,2016,Summer,Rio de Janeiro,Swimming,Swimming Women's 4 x 200 metres Freestyle Relay,Gold

In [ ]:
#Updating to include information on trends among the highest paid athletes in the world
url = "https://raw.githubusercontent.com/ali-ce/datasets/master/Most-paid-athletes/Athletes.csv"

athletes = pd.read_csv(url)

athletes.head()

,Rank,Name,Sport,Total Pay,Salary/Winnings,Endorsements,Nation,Gender,Year of birth,Birth Date,Place of Birth,Height (cm),Wikipedia Page,dbpedia Page,Image,Description
0,55,Aaron Rodgers,Football,"$22,000,000","$14,500,000","$7,500,000",United States,Male,1983,2/12/1983,"Chico, California, United States",188,http://en.wikipedia.org/wiki/Aaron_Rodgers,dbpedia.org/resource/Aaron_Rodgers,http://commons.wikimedia.org/wiki/Special:File...,"Aaron Charles Rodgers (born December 2, 1983) ..."
1,95,Adam Scott,Golf,"$17,700,000","$8,700,000","$9,000,000",Australia,Male,1980,16/07/1980,"Adelaide, Australia",183,https://en.wikipedia.org/wiki/Adam_Scott_(golfer),dbpedia.org/resource/Adam_Scott_(golfer),http://commons.wikimedia.org/wiki/Special:File...,Adam Derek Scott (born 16 July 1980) is an Aus...
2,60,Adrian Gonzalez,Baseball,"$21,500,000","$21,100,000","$400,000",United States,Male,1982,8/05/1982,"San Diego, California, United States",188,http://en.wikipedia.org/wiki/Adrian_Gonzalez,dbpedia.org/resource/Adrian_Gonzalez,http://commons.wikimedia.org/wiki/Special:File...,"Adrian Gonzalez (born May 8, 1982), also known..."
3,48,Alex Rodriguez,Baseball,"$22,900,000","$22,600,000","$300,000",United States,Male,1975,27/07/1975,New York City,190,http://en.wikipedia.org/wiki/Alex_Rodriguez,dbpedia.org/resource/Alex_Rodriguez,http://commons.wikimedia.org/wiki/Special:File...,"Alexander Emmanuel "" Alex "" Rodriguez (born Ju..."
4,93,Alfonso Soriano,Baseball,"$18,050,000","$18,000,000","$50,000",Dominican Republic,Male,1976,7/01/1976,"San Pedro de Macorís, Dominican Republic",185,http://en.wikipedia.org/wiki/Alfonso_Soriano,dbpedia.org/resource/Alfonso_Soriano,http://commons.wikimedia.org/wiki/Special:File...,"Alfonso Guilleard Soriano (born January 7, 197..."

In [ ]:
# Stripping "$" and ","
athletes["Total Pay"] = athletes["Total Pay"].str.replace("$", "", regex=False).str.replace(",", "", regex=False).astype(float)

In [ ]:
# What is the correlation between an athlete's height and their total pay?
athletes[["Height (cm)", "Total Pay"]].corr()

             Height (cm)  Total Pay
Height (cm)     1.000000  -0.114956
Total Pay      -0.114956   1.000000

In [ ]:
#Creating an age column for cleaner readability
athletes["Age"] = 2026 - athletes["Year of birth"]

In [ ]:
# What is the difference between the 75th percentile and 25th percentile of top-paid athlete ages?
athletes["Age"].quantile(0.75) - athletes["Age"].quantile(0.25)

np.float64(5.25)

In [ ]:
# Compare the mean total pay by sport. What sport has the highest paid athletes in this data, on average?
athletes.groupby("Sport")["Total Pay"].mean().sort_values(ascending=False).head(1)

Sport
Boxing    48950000.0
Name: Total Pay, dtype: float64

In [ ]:
# Updating notebook. The Basketball Account Team has identified an API that will return detailed player statistics by season.
import requests

url = "https://api.server.nbaapi.com/api/playertotals?season=2024&page=1&pageSize=1000"

response = requests.get(url)

data = response.json()

data

{'data': [{'playerId': 'doncilu01',
   'playerName': 'Luka Dončić',
   'position': 'PG',
   'age': 24,
   'games': 70,
   'gamesStarted': 70,
   'minutesPg': 2624,
   'fieldGoals': 804,
   'fieldAttempts': 1652,
   'fieldPercent': 0.487,
   'threeFg': 284,
   'threeAttempts': 744,
   'threePercent': 0.382,
   'twoFg': 520,
   'twoAttempts': 908,
   'twoPercent': 0.573,
   'effectFgPercent': 0.573,
   'ft': 478,
   'ftAttempts': 608,
   'ftPercent': 0.786,
   'offensiveRb': 59,
   'defensiveRb': 588,
   'totalRb': 647,
   'assists': 686,
   'steals': 99,
   'blocks': 38,
   'turnovers': 282,
   'personalFouls': 149,
   'points': 2370,
   'team': 'DAL',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'gilgesh01',
   'playerName': 'Shai Gilgeous-Alexander',
   'position': 'PG',
   'age': 25,
   'games': 75,
   'gamesStarted': 75,
   'minutesPg': 2553,
   'fieldGoals': 796,
   'fieldAttempts': 1487,
   'fieldPercent': 0.535,
   'threeFg': 95,
   'threeAttempts': 269,
   'threePercent': 0.353,
   'twoFg': 701,
   'twoAttempts': 1218,
   'twoPercent': 0.576,
   'effectFgPercent': 0.567,
   'ft': 567,
   'ftAttempts': 649,
   'ftPercent': 0.874,
   'offensiveRb': 65,
   'defensiveRb': 350,
   'totalRb': 415,
   'assists': 465,
   'steals': 150,
   'blocks': 67,
   'turnovers': 162,
   'personalFouls': 184,
   'points': 2254,
   'team': 'OKC',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'antetgi01',
   'playerName': 'Giannis Antetokounmpo',
   'position': 'PF',
   'age': 29,
   'games': 73,
   'gamesStarted': 73,
   'minutesPg': 2567,
   'fieldGoals': 837,
   'fieldAttempts': 1369,
   'fieldPercent': 0.611,
   'threeFg': 34,
   'threeAttempts': 124,
   'threePercent': 0.274,
   'twoFg': 803,
   'twoAttempts': 1245,
   'twoPercent': 0.645,
   'effectFgPercent': 0.624,
   'ft': 514,
   'ftAttempts': 782,
   'ftPercent': 0.657,
   'offensiveRb': 196,
   'defensiveRb': 645,
   'totalRb': 841,
   'assists': 476,
   'steals': 87,
   'blocks': 79,
   'turnovers': 250,
   'personalFouls': 210,
   'points': 2222,
   'team': 'MIL',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'brunsja01',
   'playerName': 'Jalen Brunson',
   'position': 'PG',
   'age': 27,
   'games': 77,
   'gamesStarted': 77,
   'minutesPg': 2726,
   'fieldGoals': 790,
   'fieldAttempts': 1648,
   'fieldPercent': 0.479,
   'threeFg': 211,
   'threeAttempts': 526,
   'threePercent': 0.401,
   'twoFg': 579,
   'twoAttempts': 1122,
   'twoPercent': 0.516,
   'effectFgPercent': 0.543,
   'ft': 421,
   'ftAttempts': 497,
   'ftPercent': 0.847,
   'offensiveRb': 43,
   'defensiveRb': 235,
   'totalRb': 278,
   'assists': 519,
   'steals': 70,
   'blocks': 13,
   'turnovers': 186,
   'personalFouls': 144,
   'points': 2212,
   'team': 'NYK',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'jokicni01',
   'playerName': 'Nikola Jokić',
   'position': 'C',
   'age': 28,
   'games': 79,
   'gamesStarted': 79,
   'minutesPg': 2737,
   'fieldGoals': 822,
   'fieldAttempts': 1411,
   'fieldPercent': 0.583,
   'threeFg': 83,
   'threeAttempts': 231,
   'threePercent': 0.359,
   'twoFg': 739,
   'twoAttempts': 1180,
   'twoPercent': 0.626,
   'effectFgPercent': 0.612,
   'ft': 358,
   'ftAttempts': 438,
   'ftPercent': 0.817,
   'offensiveRb': 223,
   'defensiveRb': 753,
   'totalRb': 976,
   'assists': 708,
   'steals': 108,
   'blocks': 68,
   'turnovers': 237,
   'personalFouls': 194,
   'points': 2085,
   'team': 'DEN',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'edwaran01',
   'playerName': 'Anthony Edwards',
   'position': 'SG',
   'age': 22,
   'games': 79,
   'gamesStarted': 78,
   'minutesPg': 2770,
   'fieldGoals': 718,
   'fieldAttempts': 1558,
   'fieldPercent': 0.461,
   'threeFg': 190,
   'threeAttempts': 532,
   'threePercent': 0.357,
   'twoFg': 528,
   'twoAttempts': 1026,
   'twoPercent': 0.515,
   'effectFgPercent': 0.522,
   'ft': 423,
   'ftAttempts': 506,
   'ftPercent': 0.836,
   'offensiveRb': 52,
   'defensiveRb': 378,
   'totalRb': 430,
   'assists': 405,
   'steals': 101,
   'blocks': 42,
   'turnovers': 241,
   'personalFouls': 141,
   'points': 2049,
   'team': 'MIN',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'duranke01',
   'playerName': 'Kevin Durant',
   'position': 'PF',
   'age': 35,
   'games': 75,
   'gamesStarted': 75,
   'minutesPg': 2791,
   'fieldGoals': 751,
   'fieldAttempts': 1436,
   'fieldPercent': 0.523,
   'threeFg': 168,
   'threeAttempts': 407,
   'threePercent': 0.413,
   'twoFg': 583,
   'twoAttempts': 1029,
   'twoPercent': 0.567,
   'effectFgPercent': 0.581,
   'ft': 362,
   'ftAttempts': 423,
   'ftPercent': 0.856,
   'offensiveRb': 41,
   'defensiveRb': 454,
   'totalRb': 495,
   'assists': 378,
   'steals': 69,
   'blocks': 91,
   'turnovers': 244,
   'personalFouls': 133,
   'points': 2032,
   'team': 'PHO',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'tatumja01',
   'playerName': 'Jayson Tatum',
   'position': 'PF',
   'age': 25,
   'games': 74,
   'gamesStarted': 74,
   'minutesPg': 2645,
   'fieldGoals': 672,
   'fieldAttempts': 1426,
   'fieldPercent': 0.471,
   'threeFg': 229,
   'threeAttempts': 609,
   'threePercent': 0.376,
   'twoFg': 443,
   'twoAttempts': 817,
   'twoPercent': 0.542,
   'effectFgPercent': 0.552,
   'ft': 414,
   'ftAttempts': 497,
   'ftPercent': 0.833,
   'offensiveRb': 67,
   'defensiveRb': 534,
   'totalRb': 601,
   'assists': 364,
   'steals': 75,
   'blocks': 43,
   'turnovers': 188,
   'personalFouls': 145,
   'points': 1987,
   'team': 'BOS',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'foxde01',
   'playerName': "De'Aaron Fox",
   'position': 'PG',
   'age': 26,
   'games': 74,
   'gamesStarted': 74,
   'minutesPg': 2659,
   'fieldGoals': 720,
   'fieldAttempts': 1549,
   'fieldPercent': 0.465,
   'threeFg': 214,
   'threeAttempts': 580,
   'threePercent': 0.369,
   'twoFg': 506,
   'twoAttempts': 969,
   'twoPercent': 0.522,
   'effectFgPercent': 0.534,
   'ft': 312,
   'ftAttempts': 423,
   'ftPercent': 0.738,
   'offensiveRb': 67,
   'defensiveRb': 273,
   'totalRb': 340,
   'assists': 418,
   'steals': 150,
   'blocks': 31,
   'turnovers': 194,
   'personalFouls': 193,
   'points': 1966,
   'team': 'SAC',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'curryst01',
   'playerName': 'Stephen Curry',
   'position': 'PG',
   'age': 35,
   'games': 74,
   'gamesStarted': 74,
   'minutesPg': 2421,
   'fieldGoals': 650,
   'fieldAttempts': 1445,
   'fieldPercent': 0.45,
   'threeFg': 357,
   'threeAttempts': 876,
   'threePercent': 0.408,
   'twoFg': 293,
   'twoAttempts': 569,
   'twoPercent': 0.515,
   'effectFgPercent': 0.573,
   'ft': 299,
   'ftAttempts': 324,
   'ftPercent': 0.923,
   'offensiveRb': 37,
   'defensiveRb': 293,
   'totalRb': 330,
   'assists': 379,
   'steals': 54,
   'blocks': 28,
   'turnovers': 210,
   'personalFouls': 117,
   'points': 1956,
   'team': 'GSW',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'derozde01',
   'playerName': 'DeMar DeRozan',
   'position': 'SF',
   'age': 34,
   'games': 79,
   'gamesStarted': 79,
   'minutesPg': 2989,
   'fieldGoals': 650,
   'fieldAttempts': 1355,
   'fieldPercent': 0.48,
   'threeFg': 75,
   'threeAttempts': 225,
   'threePercent': 0.333,
   'twoFg': 575,
   'twoAttempts': 1130,
   'twoPercent': 0.509,
   'effectFgPercent': 0.507,
   'ft': 522,
   'ftAttempts': 612,
   'ftPercent': 0.853,
   'offensiveRb': 43,
   'defensiveRb': 297,
   'totalRb': 340,
   'assists': 421,
   'steals': 90,
   'blocks': 45,
   'turnovers': 135,
   'personalFouls': 161,
   'points': 1897,
   'team': 'CHI',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'davisan02',
   'playerName': 'Anthony Davis',
   'position': 'C',
   'age': 30,
   'games': 76,
   'gamesStarted': 76,
   'minutesPg': 2700,
   'fieldGoals': 713,
   'fieldAttempts': 1283,
   'fieldPercent': 0.556,
   'threeFg': 29,
   'threeAttempts': 107,
   'threePercent': 0.271,
   'twoFg': 684,
   'twoAttempts': 1176,
   'twoPercent': 0.582,
   'effectFgPercent': 0.567,
   'ft': 421,
   'ftAttempts': 516,
   'ftPercent': 0.816,
   'offensiveRb': 239,
   'defensiveRb': 722,
   'totalRb': 961,
   'assists': 266,
   'steals': 91,
   'blocks': 178,
   'turnovers': 159,
   'personalFouls': 177,
   'points': 1876,
   'team': 'LAL',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'bookede01',
   'playerName': 'Devin Booker',
   'position': 'PG',
   'age': 27,
   'games': 68,
   'gamesStarted': 68,
   'minutesPg': 2447,
   'fieldGoals': 642,
   'fieldAttempts': 1305,
   'fieldPercent': 0.492,
   'threeFg': 152,
   'threeAttempts': 418,
   'threePercent': 0.364,
   'twoFg': 490,
   'twoAttempts': 887,
   'twoPercent': 0.552,
   'effectFgPercent': 0.55,
   'ft': 405,
   'ftAttempts': 457,
   'ftPercent': 0.886,
   'offensiveRb': 56,
   'defensiveRb': 252,
   'totalRb': 308,
   'assists': 472,
   'steals': 61,
   'blocks': 28,
   'turnovers': 178,
   'personalFouls': 206,
   'points': 1841,
   'team': 'PHO',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'jamesle01',
   'playerName': 'LeBron James',
   'position': 'PF',
   'age': 39,
   'games': 71,
   'gamesStarted': 71,
   'minutesPg': 2504,
   'fieldGoals': 685,
   'fieldAttempts': 1269,
   'fieldPercent': 0.54,
   'threeFg': 149,
   'threeAttempts': 363,
   'threePercent': 0.41,
   'twoFg': 536,
   'twoAttempts': 906,
   'twoPercent': 0.592,
   'effectFgPercent': 0.599,
   'ft': 303,
   'ftAttempts': 404,
   'ftPercent': 0.75,
   'offensiveRb': 61,
   'defensiveRb': 457,
   'totalRb': 518,
   'assists': 589,
   'steals': 89,
   'blocks': 38,
   'turnovers': 245,
   'personalFouls': 78,
   'points': 1822,
   'team': 'LAL',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'maxeyty01',
   'playerName': 'Tyrese Maxey',
   'position': 'PG',
   'age': 23,
   'games': 70,
   'gamesStarted': 70,
   'minutesPg': 2626,
   'fieldGoals': 638,
   'fieldAttempts': 1419,
   'fieldPercent': 0.45,
   'threeFg': 212,
   'threeAttempts': 569,
   'threePercent': 0.373,
   'twoFg': 426,
   'twoAttempts': 850,
   'twoPercent': 0.501,
   'effectFgPercent': 0.524,
   'ft': 328,
   'ftAttempts': 378,
   'ftPercent': 0.868,
   'offensiveRb': 36,
   'defensiveRb': 222,
   'totalRb': 258,
   'assists': 433,
   'steals': 69,
   'blocks': 33,
   'turnovers': 116,
   'personalFouls': 151,
   'points': 1816,
   'team': 'PHI',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'banchpa01',
   'playerName': 'Paolo Banchero',
   'position': 'PF',
   'age': 21,
   'games': 80,
   'gamesStarted': 80,
   'minutesPg': 2799,
   'fieldGoals': 640,
   'fieldAttempts': 1407,
   'fieldPercent': 0.455,
   'threeFg': 119,
   'threeAttempts': 351,
   'threePercent': 0.339,
   'twoFg': 521,
   'twoAttempts': 1056,
   'twoPercent': 0.493,
   'effectFgPercent': 0.497,
   'ft': 405,
   'ftAttempts': 559,
   'ftPercent': 0.725,
   'offensiveRb': 82,
   'defensiveRb': 472,
   'totalRb': 554,
   'assists': 431,
   'steals': 71,
   'blocks': 47,
   'turnovers': 247,
   'personalFouls': 153,
   'points': 1804,
   'team': 'ORL',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'lillada01',
   'playerName': 'Damian Lillard',
   'position': 'PG',
   'age': 33,
   'games': 73,
   'gamesStarted': 73,
   'minutesPg': 2579,
   'fieldGoals': 541,
   'fieldAttempts': 1277,
   'fieldPercent': 0.424,
   'threeFg': 220,
   'threeAttempts': 622,
   'threePercent': 0.354,
   'twoFg': 321,
   'twoAttempts': 655,
   'twoPercent': 0.49,
   'effectFgPercent': 0.51,
   'ft': 473,
   'ftAttempts': 514,
   'ftPercent': 0.92,
   'offensiveRb': 36,
   'defensiveRb': 284,
   'totalRb': 320,
   'assists': 508,
   'steals': 72,
   'blocks': 18,
   'turnovers': 193,
   'personalFouls': 134,
   'points': 1775,
   'team': 'MIL',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'murrade01',
   'playerName': 'Dejounte Murray',
   'position': 'SG',
   'age': 27,
   'games': 78,
   'gamesStarted': 78,
   'minutesPg': 2783,
   'fieldGoals': 672,
   'fieldAttempts': 1463,
   'fieldPercent': 0.459,
   'threeFg': 201,
   'threeAttempts': 554,
   'threePercent': 0.363,
   'twoFg': 471,
   'twoAttempts': 909,
   'twoPercent': 0.518,
   'effectFgPercent': 0.528,
   'ft': 208,
   'ftAttempts': 262,
   'ftPercent': 0.794,
   'offensiveRb': 62,
   'defensiveRb': 354,
   'totalRb': 416,
   'assists': 502,
   'steals': 111,
   'blocks': 24,
   'turnovers': 201,
   'personalFouls': 138,
   'points': 1753,
   'team': 'ATL',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'siakapa01',
   'playerName': 'Pascal Siakam',
   'position': 'PF',
   'age': 29,
   'games': 80,
   'gamesStarted': 80,
   'minutesPg': 2657,
   'fieldGoals': 681,
   'fieldAttempts': 1271,
   'fieldPercent': 0.536,
   'threeFg': 85,
   'threeAttempts': 246,
   'threePercent': 0.346,
   'twoFg': 596,
   'twoAttempts': 1025,
   'twoPercent': 0.581,
   'effectFgPercent': 0.569,
   'ft': 290,
   'ftAttempts': 396,
   'ftPercent': 0.732,
   'offensiveRb': 139,
   'defensiveRb': 426,
   'totalRb': 565,
   'assists': 342,
   'steals': 63,
   'blocks': 25,
   'turnovers': 141,
   'personalFouls': 193,
   'points': 1737,
   'team': '2TM',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'georgpa01',
   'playerName': 'Paul George',
   'position': 'PF',
   'age': 33,
   'games': 74,
   'gamesStarted': 74,
   'minutesPg': 2502,
   'fieldGoals': 582,
   'fieldAttempts': 1236,
   'fieldPercent': 0.471,
   'threeFg': 243,
   'threeAttempts': 588,
   'threePercent': 0.413,
   'twoFg': 339,
   'twoAttempts': 648,
   'twoPercent': 0.523,
   'effectFgPercent': 0.569,
   'ft': 264,
   'ftAttempts': 291,
   'ftPercent': 0.907,
   'offensiveRb': 37,
   'defensiveRb': 351,
   'totalRb': 388,
   'assists': 262,
   'steals': 113,
   'blocks': 37,
   'turnovers': 153,
   'personalFouls': 202,
   'points': 1671,
   'team': 'LAC',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'leonaka01',
   'playerName': 'Kawhi Leonard',
   'position': 'SF',
   'age': 32,
   'games': 68,
   'gamesStarted': 68,
   'minutesPg': 2330,
   'fieldGoals': 610,
   'fieldAttempts': 1162,
   'fieldPercent': 0.525,
   'threeFg': 140,
   'threeAttempts': 336,
   'threePercent': 0.417,
   'twoFg': 470,
   'twoAttempts': 826,
   'twoPercent': 0.569,
   'effectFgPercent': 0.585,
   'ft': 253,
   'ftAttempts': 286,
   'ftPercent': 0.885,
   'offensiveRb': 84,
   'defensiveRb': 332,
   'totalRb': 416,
   'assists': 244,
   'steals': 111,
   'blocks': 59,
   'turnovers': 119,
   'personalFouls': 97,
   'points': 1613,
   'team': 'LAC',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'brownja02',
   'playerName': 'Jaylen Brown',
   'position': 'SF',
   'age': 27,
   'games': 70,
   'gamesStarted': 70,
   'minutesPg': 2343,
   'fieldGoals': 627,
   'fieldAttempts': 1256,
   'fieldPercent': 0.499,
   'threeFg': 145,
   'threeAttempts': 410,
   'threePercent': 0.354,
   'twoFg': 482,
   'twoAttempts': 846,
   'twoPercent': 0.57,
   'effectFgPercent': 0.557,
   'ft': 211,
   'ftAttempts': 300,
   'ftPercent': 0.703,
   'offensiveRb': 84,
   'defensiveRb': 303,
   'totalRb': 387,
   'assists': 249,
   'steals': 83,
   'blocks': 37,
   'turnovers': 166,
   'personalFouls': 185,
   'points': 1610,
   'team': 'BOS',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'greenja05',
   'playerName': 'Jalen Green',
   'position': 'SG',
   'age': 21,
   'games': 82,
   'gamesStarted': 82,
   'minutesPg': 2601,
   'fieldGoals': 563,
   'fieldAttempts': 1332,
   'fieldPercent': 0.423,
   'threeFg': 201,
   'threeAttempts': 605,
   'threePercent': 0.332,
   'twoFg': 362,
   'twoAttempts': 727,
   'twoPercent': 0.498,
   'effectFgPercent': 0.498,
   'ft': 283,
   'ftAttempts': 352,
   'ftPercent': 0.804,
   'offensiveRb': 41,
   'defensiveRb': 382,
   'totalRb': 423,
   'assists': 291,
   'steals': 66,
   'blocks': 28,
   'turnovers': 191,
   'personalFouls': 115,
   'points': 1610,
   'team': 'HOU',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'bridgmi01',
   'playerName': 'Mikal Bridges',
   'position': 'SF',
   'age': 27,
   'games': 82,
   'gamesStarted': 82,
   'minutesPg': 2854,
   'fieldGoals': 564,
   'fieldAttempts': 1294,
   'fieldPercent': 0.436,
   'threeFg': 220,
   'threeAttempts': 592,
   'threePercent': 0.372,
   'twoFg': 344,
   'twoAttempts': 702,
   'twoPercent': 0.49,
   'effectFgPercent': 0.521,
   'ft': 258,
   'ftAttempts': 317,
   'ftPercent': 0.814,
   'offensiveRb': 68,
   'defensiveRb': 304,
   'totalRb': 372,
   'assists': 299,
   'steals': 81,
   'blocks': 30,
   'turnovers': 164,
   'personalFouls': 116,
   'points': 1606,
   'team': 'BRK',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'willizi01',
   'playerName': 'Zion Williamson',
   'position': 'PF',
   'age': 23,
   'games': 70,
   'gamesStarted': 70,
   'minutesPg': 2207,
   'fieldGoals': 624,
   'fieldAttempts': 1094,
   'fieldPercent': 0.57,
   'threeFg': 6,
   'threeAttempts': 18,
   'threePercent': 0.333,
   'twoFg': 618,
   'twoAttempts': 1076,
   'twoPercent': 0.574,
   'effectFgPercent': 0.573,
   'ft': 347,
   'ftAttempts': 494,
   'ftPercent': 0.702,
   'offensiveRb': 122,
   'defensiveRb': 284,
   'totalRb': 406,
   'assists': 352,
   'steals': 77,
   'blocks': 47,
   'turnovers': 193,
   'personalFouls': 159,
   'points': 1601,
   'team': 'NOP',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'sabondo01',
   'playerName': 'Domantas Sabonis',
   'position': 'C',
   'age': 27,
   'games': 82,
   'gamesStarted': 82,
   'minutesPg': 2928,
   'fieldGoals': 634,
   'fieldAttempts': 1068,
   'fieldPercent': 0.594,
   'threeFg': 33,
   'threeAttempts': 87,
   'threePercent': 0.379,
   'twoFg': 601,
   'twoAttempts': 981,
   'twoPercent': 0.613,
   'effectFgPercent': 0.609,
   'ft': 292,
   'ftAttempts': 415,
   'ftPercent': 0.704,
   'offensiveRb': 294,
   'defensiveRb': 826,
   'totalRb': 1120,
   'assists': 673,
   'steals': 74,
   'blocks': 48,
   'turnovers': 272,
   'personalFouls': 250,
   'points': 1593,
   'team': 'SAC',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'kuzmaky01',
   'playerName': 'Kyle Kuzma',
   'position': 'PF',
   'age': 28,
   'games': 70,
   'gamesStarted': 70,
   'minutesPg': 2281,
   'fieldGoals': 608,
   'fieldAttempts': 1313,
   'fieldPercent': 0.463,
   'threeFg': 151,
   'threeAttempts': 450,
   'threePercent': 0.336,
   'twoFg': 457,
   'twoAttempts': 863,
   'twoPercent': 0.53,
   'effectFgPercent': 0.521,
   'ft': 186,
   'ftAttempts': 240,
   'ftPercent': 0.775,
   'offensiveRb': 62,
   'defensiveRb': 402,
   'totalRb': 464,
   'assists': 296,
   'steals': 37,
   'blocks': 49,
   'turnovers': 192,
   'personalFouls': 153,
   'points': 1553,
   'team': 'WAS',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'wembavi01',
   'playerName': 'Victor Wembanyama',
   'position': 'C',
   'age': 20,
   'games': 71,
   'gamesStarted': 71,
   'minutesPg': 2106,
   'fieldGoals': 551,
   'fieldAttempts': 1186,
   'fieldPercent': 0.465,
   'threeFg': 128,
   'threeAttempts': 394,
   'threePercent': 0.325,
   'twoFg': 423,
   'twoAttempts': 792,
   'twoPercent': 0.534,
   'effectFgPercent': 0.519,
   'ft': 292,
   'ftAttempts': 367,
   'ftPercent': 0.796,
   'offensiveRb': 161,
   'defensiveRb': 594,
   'totalRb': 755,
   'assists': 274,
   'steals': 88,
   'blocks': 254,
   'turnovers': 260,
   'personalFouls': 153,
   'points': 1522,
   'team': 'SAS',
   'season': 2024,
   'isPlayoff': False},
  {'playerId': 'whiteco01',
   'playerName': 'Coby White',
   'position': 'PG',
   'age': 23,
   'games': 79,
   'gamesStarted': 78,
   'minutesPg': 2881,
   'fieldGoals': 541,
   'fieldAttempts': 1209,
   'fieldPercent': 0.447,
   'threeFg': 209,
   'threeAttempts': 556,
   'threePercent': 0.376,
   'twoFg': 332,
   'twoAttempts': 653,
   'twoPercent': 0.508,
   'effectFgPercent': 0.534,
   'ft': 218,
   'ftAttempts': 260,
   'ftPercent': 0.838,

In [ ]:
nba_players = pd.DataFrame(data["data"])

nba_players.head()

,playerId,playerName,position,age,games,gamesStarted,minutesPg,fieldGoals,fieldAttempts,fieldPercent,...,totalRb,assists,steals,blocks,turnovers,personalFouls,points,team,season,isPlayoff
0,doncilu01,Luka Dončić,PG,24,70,70,2624,804,1652,0.487,...,647,686,99,38,282,149,2370,DAL,2024,False
1,gilgesh01,Shai Gilgeous-Alexander,PG,25,75,75,2553,796,1487,0.535,...,415,465,150,67,162,184,2254,OKC,2024,False
2,antetgi01,Giannis Antetokounmpo,PF,29,73,73,2567,837,1369,0.611,...,841,476,87,79,250,210,2222,MIL,2024,False
3,brunsja01,Jalen Brunson,PG,27,77,77,2726,790,1648,0.479,...,278,519,70,13,186,144,2212,NYK,2024,False
4,jokicni01,Nikola Jokić,C,28,79,79,2737,822,1411,0.583,...,976,708,108,68,237,194,2085,DEN,2024,False

In [ ]:
#What is the maximum number of games started by a player in the 2024 season?
nba_players["gamesStarted"].max()

82

In [ ]:
#How many players started that number of games in the 2024 season?
(nba_players["gamesStarted"] == nba_players["gamesStarted"].max()).sum()

np.int64(4)

In [ ]:
all_players = []

for page in range(1, 20):
    url = f"https://api.server.nbaapi.com/api/playertotals?season=2024&page={page}&pageSize=1000"
    response = requests.get(url)
    page_data = response.json()

    all_players.extend(page_data["data"])

nba_players = pd.DataFrame(all_players)

nba_players.shape

(949, 32)

In [ ]:
# Create a list of the 10 underused players with the highest "stocks per game."
nba_players["stocks_per_game"] = (
    (nba_players["steals"] + nba_players["blocks"])
    / nba_players["games"]
)

nba_players["minutes_per_game"] = (
    nba_players["minutesPg"]
    / nba_players["games"]
)

top10 = (
    nba_players[nba_players["minutes_per_game"] < 25]
    .sort_values("stocks_per_game", ascending=False)
    .head(10)
)

top10[["playerName", "stocks_per_game", "minutes_per_game"]]

             playerName  stocks_per_game  minutes_per_game
140      Daniel Gafford         2.945946         24.527027
224      Walker Kessler         2.875000         23.328125
837    Robert Covington         2.666667         23.000000
322      Daniel Gafford         2.655172         21.482759
303    Matisse Thybulle         2.492308         22.876923
685     Robert Williams         2.333333         19.833333
842       Nicolas Batum         2.333333         18.000000
461   Mitchell Robinson         2.322581         24.774194
579  Kristaps Porziņģis         2.285714         23.571429
406          Tari Eason         2.272727         21.818182

In [ ]:
# Install Kaggle library
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.19.4)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.6.17)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.10.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.16.0)

In [ ]:
import os

os.environ["KAGGLE_API_TOKEN"] = "KGAT_fdff8e850ad44900af2fb6744907b9c3"

In [ ]:
!kaggle datasets download -d rishidamarla/2017-espn-athletes-fame-rankings

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/rishidamarla/2017-espn-athletes-fame-rankings
License(s): CC0-1.0
Downloading 2017-espn-athletes-fame-rankings.zip to /content
100% 16.7k/16.7k [00:00<00:00, 28.5MB/s]

In [ ]:
!unzip -o 2017-espn-athletes-fame-rankings.zip

Archive:  2017-espn-athletes-fame-rankings.zip
  inflating: 2017 ESPN World Fame 100.xlsx

In [ ]:
os.listdir()

['.config',
 '2017-espn-athletes-fame-rankings.zip',
 '2017 ESPN World Fame 100.xlsx',
 'female_olympic_swimmers.csv',
 'sample_data']

In [ ]:
social_media = pd.read_excel("2017 ESPN World Fame 100.xlsx")

social_media.columns

Index(['Rank', 'PY Rank', 'Last Name', 'First Name', 'Sport', 'Country',
       'Team', 'Endorsements', 'Instgram Followers', 'Facebook Followers',
       'Twitter Followers', 'Endorsements.1', 'Instgram Followers.1',
       'Facebook Followers.1', 'Twitter Followers.1'],
      dtype='object')

In [ ]:
# What social media presence has the highest correlation with endorsements?
corr = social_media[
    ["Endorsements",
     "Instgram Followers",
     "Facebook Followers",
     "Twitter Followers"]
].corr()["Endorsements"]

corr.drop("Endorsements").idxmax()

'Twitter Followers'

In [ ]:
# Gathering follower information
social_media["Total Followers"] = (
    social_media["Instgram Followers"] +
    social_media["Facebook Followers"] +
    social_media["Twitter Followers"]
)

In [ ]:
# Which sport has the highest average total followers?
social_media.groupby("Sport")["Total Followers"].mean().sort_values(ascending=False)

Sport
Soccer             41.509111
Cricket            31.400000
Track and Field    30.000000
Basketball         22.795273
MMA                20.166667
Tennis             12.945200
Boxing              9.745000
Formula One         8.184500
Football            7.822000
NASCAR              4.522500
Gymnastics          4.509000
Golf                3.696429
Swimming            2.798000
Badminton                NaN
Table Tennis             NaN
Name: Total Followers, dtype: float64

In [ ]:
# Which sport has the highest average endorsements
social_media.groupby("Sport")["Endorsements"].mean().sort_values(ascending=False)

Sport
Track and Field    30.000000
Tennis             23.350000
Golf               21.363636
Basketball         18.423077
Football            8.875000
Cricket             8.759750
NASCAR              8.000000
Soccer              7.018333
MMA                 6.666667
Formula One         5.500000
Boxing              2.000000
Swimming            1.150000
Gymnastics          1.075000
Badminton                NaN
Table Tennis             NaN
Name: Endorsements, dtype: float64